platform :ios, '9.0'

use_frameworks!

target 'AKSwiftAuth0Test' do
    pod 'Lock', '~> 1.26'
    pod 'SimpleKeychain'
    pod 'Auth0', '~> 1.0.0-beta.7'
end

post_install do |installer|
    installer.pods_project.build_configurations.each { |bc|
        bc.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    }
end